# Generated by Django 2.1.7 on 2019-03-22 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(default=datetime.date.today)),
                ('departure_time', models.TimeField()),
                ('destination', models.CharField(max_length=25)),
                ('departure_railway', models.CharField(max_length=25)),
                ('departure_platform', models.IntegerField()),
                ('destination_railway', models.CharField(max_length=25)),
                ('price_of_ticket', models.FloatField()),
                ('route_number', models.IntegerField()),
                ('bus_brand', models.CharField(max_length=25)),
                ('travel_time', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(default=datetime.date.today)),
                ('departure_time', models.TimeField()),
                ('destination', models.CharField(max_length=25)),
                ('departure_railway', models.CharField(max_length=25)),
                ('departure_platform', models.IntegerField()),
                ('destination_railway', models.CharField(max_length=25)),
                ('price_of_ticket', models.FloatField()),
                ('train_number', models.IntegerField()),
                ('destination_date', models.DateField()),
                ('destination_time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
